dist: xenial
os: linux
language: node_js
node_js:
  - node
install:
  - npm ci
before_script:
  - node --version
  - npm --version
script:
  - npm run htmllint
  - npm run stylelint
notifications:
  irc:
    channels:
      - "chat.freenode.net#miraheze-bots"
    on_success: change
    on_failure: always
    template:
      - "%{repository}/%{branch}/%{commit} - %{author} %{message} %{build_url}"
