dist: xenial
os: linux
install:
  - npm ci
script:
  - npm run stylelint && npm run htmllint
notifications:
  irc:
    channels:
      - "chat.freenode.net#ZppixBot"
    on_success: change
    on_failure: always
    template:
      - "%{repository}/%{branch}/%{commit} - %{author} %{message} %{build_url}"
