dist: xenial
os: linux
language: generic
install:
  - npm ci
before_script:
  - node --version
  - npm --version
script:
  - npm run stylelint
  - npm run htmllint
notifications:
  irc:
    channels:
      - "chat.freenode.net#ZppixBot"
    on_success: change
    on_failure: always
    template:
      - "%{repository}/%{branch}/%{commit} - %{author} %{message} %{build_url}"
